name: terraform-management
on:
  push: {}
  pull_request: {}

permissions:
  pull-requests: write

jobs:
  terraform:
    uses: BobyMCbobs/sample-terraform-monorepo/.github/workflows/reusable-terraform-management.yml@main
    with:
      terraformCloudApiToken: ${{ secrets.TF_API_TOKEN }}
